spring.application.name: zuul-server
server.port: 48450
eureka.client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl.defaultZone: ${EUREKA_URI:http://localhost:48460/eureka}

zuul:
  ignoredServices: '*'
  routes:
    isu:
      path: /isu/**
      serviceId: svc2
